branchName: '${issue.number}-${issue.title,}'
openDraftPR: true
autoCloseIssue: true
gitSafeReplacementChar: '-'
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
branches:
  - label: enhancement
    prefix: feature-
  - label: bug
    prefix: bug-
